# Generated by Django 5.2.11 on 2026-05-08 06:29

import apps.partners.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "commission_percent",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="% of post-discount revenue paid to the partner on first payment.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            (
                                "paused",
                                "Paused — links still work but no new commissions",
                            ),
                            ("terminated", "Terminated — links disabled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("wise", "Wise"),
                            ("paypal", "PayPal"),
                            ("bank", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        default="wise",
                        max_length=16,
                    ),
                ),
                (
                    "payout_details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text payout details (account number, PayPal email, IBAN, etc.).",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "partners_partner",
            },
        ),
        migrations.CreateModel(
            name="PartnerAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("attributed_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        default=apps.partners.models._default_attribution_expiry,
                    ),
                ),
                (
                    "landing_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partners_partnerattribution",
            },
        ),
        migrations.CreateModel(
            name="PartnerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("wise", "Wise"),
                            ("paypal", "PayPal"),
                            ("bank", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        default="wise",
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Transaction id / Wise transfer id / bank reference.",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "db_table": "partners_partnerpayout",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referee_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "payment_id",
                    models.CharField(
                        db_index=True,
                        help_text="Dodo payment_id for this transaction.",
                        max_length=255,
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Pre-discount price.", max_digits=12
                    ),
                ),
                (
                    "post_discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What Dodo actually charged the customer (commission base).",
                        max_digits=12,
                    ),
                ),
                (
                    "commission_percent_snapshot",
                    models.PositiveSmallIntegerField(
                        help_text="Partner's commission_percent at the time this row was created."
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — owed to partner"),
                            ("paid", "Paid — payout recorded"),
                            ("cancelled", "Cancelled — refund/chargeback or fraud"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="partners.partnerattribution",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="partners.partner",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="partners.partnerpayout",
                    ),
                ),
            ],
            options={
                "db_table": "partners_partnercommission",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment_id",),
                        name="partners_unique_commission_per_payment",
                    )
                ],
            },
        ),
    ]
