# Generated by Django 5.2.6 on 2026-05-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="audience_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Self-reported audience bucket: '<1k', '1k-10k', '10k-100k', '100k-1m', '1m+'.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 3166-1 alpha-2 code (e.g. 'US', 'IN', 'DE').",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="social_platforms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of {"platform": "...", "handle": "..."} entries.',
            ),
        ),
    ]
