# Generated by Django 5.2.6 on 2026-05-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_partner_audience_size_partner_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="payout_method",
            field=models.CharField(
                choices=[
                    ("wise", "Wise"),
                    ("paypal", "PayPal"),
                    ("bank", "Bank transfer"),
                    ("crypto", "Crypto wallet"),
                    ("other", "Other"),
                ],
                default="wise",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="partnerpayout",
            name="method",
            field=models.CharField(
                choices=[
                    ("wise", "Wise"),
                    ("paypal", "PayPal"),
                    ("bank", "Bank transfer"),
                    ("crypto", "Crypto wallet"),
                    ("other", "Other"),
                ],
                default="wise",
                max_length=16,
            ),
        ),
    ]
