# Generated by Django 5.2.11 on 2026-05-25 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_remove_org_email_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "environment",
                    models.CharField(
                        choices=[("live", "Live"), ("test", "Test")],
                        default="live",
                        max_length=10,
                    ),
                ),
                ("key_prefix", models.CharField(max_length=20)),
                ("key_last4", models.CharField(max_length=4)),
                (
                    "key_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "created_by_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicApiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.CharField(max_length=80)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                ("duration_ms", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="public_api.apikey",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_api_usage",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="public_api__organiz_10311e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicapiusage",
            index=models.Index(
                fields=["organization", "-timestamp"],
                name="public_api__organiz_78f6d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicapiusage",
            index=models.Index(
                fields=["api_key", "-timestamp"], name="public_api__api_key_c75b24_idx"
            ),
        ),
    ]
