# Generated by Django 5.2.11 on 2026-05-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0045_merge_20260514_1425"),
        ("organizations", "0003_remove_org_email_unique"),
        ("public_api", "0002_webhook_webhookdelivery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NextJsDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, default="", max_length=40)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("preview", "Preview"),
                            ("development", "Development"),
                        ],
                        default="production",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=2048)),
                ("host", models.CharField(blank=True, default="", max_length=40)),
                ("build_metadata", models.JSONField(blank=True, default=dict)),
                ("pages_metadata", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nextjs_deployments",
                        to="analyzer.analysisrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nextjs_deployments",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="public_api__organiz_d01a9d_idx",
                    ),
                    models.Index(
                        fields=["commit_sha"], name="public_api__commit__9db09d_idx"
                    ),
                ],
            },
        ),
    ]
