# Generated by Django 5.2.11 on 2026-06-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_api", "0003_nextjsdeployment"),
    ]

    operations = [
        migrations.AddField(
            model_name="nextjsdeployment",
            name="signing_key_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nextjsdeployment",
            name="snapshot_origin",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="nextjsdeployment",
            name="snapshot_routes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="nextjsdeployment",
            name="snapshot_supported",
            field=models.BooleanField(default=False),
        ),
    ]
