# Generated by Django 5.2.11 on 2026-05-07 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("code", models.CharField(db_index=True, max_length=12, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "referrals_referralcode",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "referee_email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("code_used", models.CharField(max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — awaiting first payment"),
                            ("paid", "Paid — discounts triggered"),
                            ("cancelled", "Referee cancelled before discount fired"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "referee_discount_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "referrer_discount_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "referrals_referral",
                "indexes": [
                    models.Index(
                        fields=["referrer_email", "status"],
                        name="referrals_r_referre_430b60_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer_email", models.EmailField(db_index=True, max_length=254)),
                ("percent_off", models.PositiveSmallIntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — discount staged for next renewal"),
                            ("applied", "Applied — referrer's invoice was discounted"),
                            (
                                "revoked",
                                "Revoked — referee cancelled before discount fired",
                            ),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "dodo_discount_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referral",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward",
                        to="referrals.referral",
                    ),
                ),
            ],
            options={
                "db_table": "referrals_referralreward",
            },
        ),
    ]
