# Generated by Django 5.2.11 on 2026-05-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralreward",
            name="refund_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of failed refund calls — REVOKED after MAX_REFUND_ATTEMPTS.",
            ),
        ),
    ]
