# Generated by Django 5.2.11 on 2026-03-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="accounts_user",
        ),
    ]
