# Generated by Django 5.2.11 on 2026-03-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_table'),
        ('accounts', '0002_subscription'),
    ]

    operations = [
    ]
