# Generated by Django 5.2.11 on 2026-03-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_rename_user_table_0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
