# Generated by Django 5.2.11 on 2026-03-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
