# Generated by Django 5.2.6 on 2026-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_plan_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_invoice_payment_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
