# Generated by Django 5.2.6 on 2026-04-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_subscription_last_invoice_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[("starter", "Starter"), ("pro", "Pro"), ("business", "Max")],
                default="starter",
                max_length=20,
            ),
        ),
    ]
