# Generated by Django 5.2.6 on 2026-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
