# Generated by Django 5.2.11 on 2026-05-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invoicerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_billing_emails_payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
