# Generated by Django 5.2.6 on 2026-05-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_phone_number_user_profile_photo_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_billing_emails_payment_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="subscription",
            name="welcome_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
