# Generated by Django 5.2.11 on 2026-06-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_invoicerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_seen_product_tour",
            field=models.BooleanField(default=False),
        ),
    ]
