# Generated by Django 5.2.6 on 2026-02-23 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0002_alter_organization_options_organization_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google_analytics", "Google Analytics"),
                            ("shopify", "Shopify"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("access_token_encrypted", models.TextField(blank=True, default="")),
                ("refresh_token_encrypted", models.TextField(blank=True, default="")),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GADataSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("sessions", models.IntegerField(default=0)),
                ("organic_sessions", models.IntegerField(default=0)),
                ("bounce_rate", models.FloatField(default=0)),
                ("avg_session_duration", models.FloatField(default=0)),
                ("top_pages", models.JSONField(blank=True, default=list)),
                ("traffic_sources", models.JSONField(blank=True, default=list)),
                ("daily_trend", models.JSONField(blank=True, default=list)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ga_snapshots",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["provider"], name="integration_provide_2529c5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integration",
            unique_together={("organization", "provider")},
        ),
        migrations.AddIndex(
            model_name="gadatasnapshot",
            index=models.Index(
                fields=["integration", "-created_at"],
                name="integration_integra_94ea3a_idx",
            ),
        ),
    ]
