# Generated by Django 5.2.6 on 2026-02-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_shopifydatasnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google_analytics", "Google Analytics"),
                    ("shopify", "Shopify"),
                    ("wordpress", "WordPress"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="WordPressDataSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("total_posts", models.IntegerField(default=0)),
                ("total_pages", models.IntegerField(default=0)),
                ("published_posts_30d", models.IntegerField(default=0)),
                ("updated_posts_30d", models.IntegerField(default=0)),
                ("top_posts", models.JSONField(blank=True, default=list)),
                ("daily_publishing", models.JSONField(blank=True, default=list)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordpress_snapshots",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "-created_at"],
                        name="integration_integra_wp_idx",
                    )
                ],
            },
        ),
    ]
