# Generated by Django 5.2.11 on 2026-03-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_wordpressdatasnapshot_and_provider'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wordpressdatasnapshot',
            new_name='integration_integra_579d05_idx',
            old_name='integration_integra_wp_idx',
        ),
    ]
