# Generated by Django 5.2.11 on 2026-03-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_wordpressdatasnapshot_and_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="WooCommerceDataSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_products", models.IntegerField(default=0)),
                ("total_customers", models.IntegerField(default=0)),
                ("top_products", models.JSONField(blank=True, default=list)),
                ("daily_orders", models.JSONField(blank=True, default=list)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        # WordPress index rename is handled only by
        # 0004_rename_integration_integra_wp_idx_integration_integra_579d05_idx
        # (parallel 0004); duplicate RenameIndex here breaks deploy when that
        # migration runs first and renames the index before this file applies.
        migrations.AlterField(
            model_name="integration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google_analytics", "Google Analytics"),
                    ("shopify", "Shopify"),
                    ("wordpress", "WordPress"),
                    ("woocommerce", "WooCommerce"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="woocommercedatasnapshot",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="woocommerce_snapshots",
                to="integrations.integration",
            ),
        ),
        migrations.AddIndex(
            model_name="woocommercedatasnapshot",
            index=models.Index(
                fields=["integration", "-created_at"],
                name="integration_integra_a5804d_idx",
            ),
        ),
    ]
