# Generated by Django 5.2.11 on 2026-03-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_rename_integration_integra_wp_idx_integration_integra_579d05_idx'),
        ('integrations', '0004_woocommerce'),
    ]

    operations = [
    ]
