# Generated by Django 5.2.6 on 2026-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_merge_20260323_2042"),
    ]

    operations = [
        migrations.AddField(
            model_name="gadatasnapshot",
            name="countries",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
