# Generated by Django 5.2.11 on 2026-05-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_ga_snapshot_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google_analytics", "Google Analytics"),
                    ("shopify", "Shopify"),
                    ("wordpress", "WordPress"),
                    ("woocommerce", "WooCommerce"),
                    ("webflow", "Webflow"),
                ],
                max_length=30,
            ),
        ),
    ]
