# Generated by Django 5.2.6 on 2026-02-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0002_alter_organization_options_organization_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("single_page", "Single Page"),
                            ("full_site", "Full Site"),
                        ],
                        default="single_page",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("crawling", "Crawling"),
                            ("analyzing", "Analyzing"),
                            ("scoring", "Scoring"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("composite_score", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_runs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIVisibilityProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_used", models.TextField()),
                ("llm_response", models.TextField(blank=True, default="")),
                ("brand_mentioned", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_probes",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("content_score", models.FloatField(default=0)),
                ("content_details", models.JSONField(default=dict)),
                ("schema_score", models.FloatField(default=0)),
                ("schema_details", models.JSONField(default=dict)),
                ("eeat_score", models.FloatField(default=0)),
                ("eeat_details", models.JSONField(default=dict)),
                ("technical_score", models.FloatField(default=0)),
                ("technical_details", models.JSONField(default=dict)),
                ("entity_score", models.FloatField(default=0)),
                ("entity_details", models.JSONField(default=dict)),
                ("ai_visibility_score", models.FloatField(default=0)),
                ("ai_visibility_details", models.JSONField(default=dict)),
                ("composite_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_scores",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-composite_score"],
            },
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=2048)),
                ("industry", models.CharField(blank=True, default="", max_length=255)),
                ("composite_score", models.FloatField(blank=True, null=True)),
                ("scored", models.BooleanField(default=False)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="analyzer.analysisrun",
                    ),
                ),
                (
                    "page_score",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitor",
                        to="analyzer.pagescore",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pillar", models.CharField(max_length=30)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("action", models.TextField()),
                (
                    "impact_estimate",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("category", models.CharField(max_length=30)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "pillar"],
            },
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(fields=["email"], name="analyzer_an_email_356346_idx"),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(fields=["status"], name="analyzer_an_status_6d5b42_idx"),
        ),
    ]
