# Generated by Django 5.2.6 on 2026-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="llm_logs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
