# Generated by Django 5.2.6 on 2026-02-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_analysisrun_llm_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="brand_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="BrandVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_score", models.FloatField(default=0)),
                ("google_details", models.JSONField(default=dict)),
                ("reddit_score", models.FloatField(default=0)),
                ("reddit_details", models.JSONField(default=dict)),
                ("medium_score", models.FloatField(default=0)),
                ("medium_details", models.JSONField(default=dict)),
                ("overall_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_visibility",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
        ),
    ]
