# Generated by Django 5.2.6 on 2026-02-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_analysisrun_brand_name_brandvisibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandvisibility",
            name="web_mentions_details",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="brandvisibility",
            name="web_mentions_score",
            field=models.FloatField(default=0),
        ),
    ]
