# Generated by Django 5.2.6 on 2026-02-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0004_brandvisibility_web_mentions_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGamification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("points_this_week", models.IntegerField(default=0)),
                ("points_this_month", models.IntegerField(default=0)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Learner"),
                            (3, "Implementer"),
                            (4, "Optimizer"),
                            (5, "Expert"),
                            (6, "Master"),
                            (7, "Legend"),
                        ],
                        default=1,
                    ),
                ),
                ("current_level_points", models.IntegerField(default=0)),
                ("points_to_next_level", models.IntegerField(default=100)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_action_date", models.DateField(blank=True, null=True)),
                ("total_actions_completed", models.IntegerField(default=0)),
                ("total_actions_verified", models.IntegerField(default=0)),
                ("total_score_improvement", models.FloatField(default=0)),
                ("achievements", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User Gamification",
            },
        ),
        migrations.CreateModel(
            name="UserAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("add_faq", "Add FAQ Section"),
                            ("add_structure", "Improve Content Structure"),
                            ("add_citations", "Add Citations & References"),
                            ("improve_readability", "Improve Readability"),
                            ("add_schema", "Add Schema Markup"),
                            ("add_article_schema", "Add Article Schema"),
                            ("add_faq_schema", "Add FAQ Schema"),
                            ("add_robots", "Create robots.txt"),
                            ("add_sitemap", "Create sitemap.xml"),
                            ("add_llms_txt", "Create llms.txt"),
                            ("enable_https", "Enable HTTPS"),
                            ("add_author", "Add Author Information"),
                            ("add_about", "Add About Page"),
                            ("add_contact", "Add Contact Page"),
                            ("add_privacy", "Add Privacy Policy"),
                            ("create_wikipedia", "Create Wikipedia Page"),
                            ("add_social", "Add Social Profiles"),
                            ("post_reddit", "Post on Reddit"),
                            ("post_medium", "Publish on Medium"),
                            ("build_backlinks", "Build Backlinks"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("points_value", models.IntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("verified", "Verified (Score Improved)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("score_before", models.FloatField(blank=True, null=True)),
                ("score_after", models.FloatField(blank=True, null=True)),
                ("score_improvement", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_actions",
                        to="analyzer.analysisrun",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_actions",
                        to="analyzer.recommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_email", "status"],
                        name="analyzer_us_user_em_b71c48_idx",
                    ),
                    models.Index(
                        fields=["user_email", "-created_at"],
                        name="analyzer_us_user_em_d946fa_idx",
                    ),
                ],
            },
        ),
    ]
