# Generated by Django 5.2.6 on 2026-03-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0007_analysisrun_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("chatgpt", "ChatGPT"),
                            ("claude", "Claude"),
                            ("gemini", "Gemini"),
                            ("perplexity", "Perplexity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_text", models.TextField(blank=True)),
                ("brand_mentioned", models.BooleanField(default=False)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("rank_position", models.IntegerField(default=0)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["checked_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_text", models.TextField()),
                ("is_custom", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="analysisrun",
            new_name="analyzer_an_slug_8ee6c2_idx",
            old_name="analyzer_an_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="blogautomationconfig",
            new_name="analyzer_bl_user_em_d6d7da_idx",
            old_name="analyzer_bl_user_em_4897d8_idx",
        ),
        migrations.RenameIndex(
            model_name="blogautomationjob",
            new_name="analyzer_bl_user_em_2de2ac_idx",
            old_name="analyzer_bl_user_em_158e58_idx",
        ),
        migrations.RenameIndex(
            model_name="blogautomationjob",
            new_name="analyzer_bl_schedul_7f349d_idx",
            old_name="analyzer_bl_schedul_d561a8_idx",
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name="useraction",
            index=models.Index(
                fields=["analysis_run_id"], name="analyzer_us_analysi_129cda_idx"
            ),
        ),
        migrations.AddField(
            model_name="prompttrack",
            name="analysis_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_tracks",
                to="analyzer.analysisrun",
            ),
        ),
        migrations.AddField(
            model_name="promptresult",
            name="prompt_track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="analyzer.prompttrack",
            ),
        ),
    ]
