# Generated by Django 5.2.11 on 2026-03-19 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0010_analysisrun_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoImprovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                (
                    "improvement_type",
                    models.CharField(
                        choices=[
                            ("meta_title", "Meta Title"),
                            ("meta_description", "Meta Description"),
                            ("hreflang", "Hreflang Tag"),
                            ("schema_markup", "Schema Markup"),
                            ("alt_text", "Image Alt Text"),
                            ("geo_meta", "Geo Meta Tag"),
                            ("content_update", "Content Update"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "resource_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "field_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("score_before", models.FloatField(blank=True, null=True)),
                ("score_after", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_improvements",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis_run", "status"],
                        name="analyzer_ge_analysi_1a1b54_idx",
                    )
                ],
            },
        ),
    ]
