# Generated by Django 5.2.11 on 2026-03-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_analysisrun_country'),
        ('integrations', '0004_woocommerce'),
        ('organizations', '0003_remove_org_email_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFixJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_type', models.CharField(choices=[('schema_markup', 'Schema Markup'), ('meta_description', 'Meta Description'), ('faq_section', 'Faq Section')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload_sent', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_fix_jobs', to='analyzer.analysisrun')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_fix_jobs', to='integrations.integration')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_fix_jobs', to='analyzer.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('url', models.URLField(max_length=2048)),
                ('brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_slug', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_analyses', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['next_run_at', 'is_active'], name='analyzer_sc_next_ru_f4f9a7_idx')],
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
