# Generated by Django 5.2.11 on 2026-03-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_autofixjob_scheduledanalysis'),
        ('analyzer', '0011_geo_improvement'),
    ]

    operations = [
    ]
