# Generated by Django 5.2.11 on 2026-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_merge_20260323_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pagescore',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
