# Generated by Django 5.2.11 on 2026-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_add_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='why',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
