# Generated by Django 5.2.11 on 2026-03-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_add_rec_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttrack',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
