# Generated by Django 5.2.6 on 2026-04-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0015_add_prompt_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autofixjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                    ("manual", "Manual"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="promptresult",
            name="engine",
            field=models.CharField(
                choices=[
                    ("chatgpt", "ChatGPT"),
                    ("claude", "Claude"),
                    ("gemini", "Gemini"),
                    ("perplexity", "Perplexity"),
                    ("google", "Google"),
                ],
                max_length=20,
            ),
        ),
    ]
