# Generated by Django 5.2.11 on 2026-04-06 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0016_auto_fix_job_status_manual_skipped'),
        ('integrations', '0005_merge_20260323_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofixjob',
            name='fix_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='autofixjob',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_fix_jobs', to='integrations.integration'),
        ),
        migrations.AlterField(
            model_name='autofixjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('manual', 'Manual'), ('skipped', 'Skipped'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
    ]
