# Generated by Django 5.2.11 on 2026-04-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0017_auto_fix_job_nullable_integration_verified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='difficulty',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='estimated_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='xp_reward',
            field=models.IntegerField(default=0),
        ),
    ]
