# Generated by Django 5.2.11 on 2026-04-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0018_add_recommendation_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='finding_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
