# Generated by Django 5.2.6 on 2026-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0018_add_recommendation_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="onboarding_prompts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
