# Generated by Django 5.2.6 on 2026-04-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0019_add_finding_key"),
        ("analyzer", "0020_recommendation_finding_code"),
    ]

    operations = []
