# Generated by Django 5.2.6 on 2026-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0021_merge_20260414_1057"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandvisibility",
            name="social_presence_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Instagram/Facebook public metrics and derived presence scores",
            ),
        ),
    ]
