# Generated by Django 5.2.6 on 2026-04-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0022_brandvisibility_social_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandvisibility",
            name="ai_brand_facts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="LLM-grounded notes on how AI may reflect the brand from visibility signals",
            ),
        ),
    ]
