# Generated by Django 5.2.11 on 2026-04-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0023_brandvisibility_ai_brand_facts"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompttrack",
            name="authority_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="prompttrack",
            name="content_quality_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="prompttrack",
            name="semantic_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="prompttrack",
            name="structural_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="prompttrack",
            name="third_party_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="promptresult",
            name="engine",
            field=models.CharField(
                choices=[
                    ("chatgpt", "ChatGPT"),
                    ("claude", "Claude"),
                    ("gemini", "Gemini"),
                    ("perplexity", "Perplexity"),
                    ("google", "Google"),
                    ("bing", "Bing"),
                ],
                max_length=20,
            ),
        ),
    ]
