# Generated by Django 5.2.11 on 2026-04-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0025_remove_medium_from_brandvisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttrack',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('add_faq', 'Add FAQ Section'), ('add_structure', 'Improve Content Structure'), ('add_citations', 'Add Citations & References'), ('improve_readability', 'Improve Readability'), ('add_schema', 'Add Schema Markup'), ('add_article_schema', 'Add Article Schema'), ('add_faq_schema', 'Add FAQ Schema'), ('add_robots', 'Create robots.txt'), ('add_sitemap', 'Create sitemap.xml'), ('add_llms_txt', 'Create llms.txt'), ('enable_https', 'Enable HTTPS'), ('add_author', 'Add Author Information'), ('add_about', 'Add About Page'), ('add_contact', 'Add Contact Page'), ('add_privacy', 'Add Privacy Policy'), ('create_wikipedia', 'Create Wikipedia Page'), ('add_social', 'Add Social Profiles'), ('post_reddit', 'Post on Reddit'), ('build_backlinks', 'Build Backlinks')], max_length=30),
        ),
    ]
