# Generated by Django 5.2.11 on 2026-04-21 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0026_prompttrack_deleted_at_alter_useraction_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('snippet', models.TextField(blank=True, default='')),
                ('position', models.IntegerField(default=0)),
                ('is_brand', models.BooleanField(db_index=True, default=False)),
                ('is_competitor', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='analyzer.promptresult')),
            ],
            options={
                'ordering': ['prompt_result_id', 'position', 'id'],
                'indexes': [models.Index(fields=['domain', 'is_brand'], name='analyzer_pr_domain_2114d7_idx'), models.Index(fields=['domain', 'is_competitor'], name='analyzer_pr_domain_98784c_idx')],
            },
        ),
    ]
