# Generated by Django 5.2.11 on 2026-04-22 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0027_promptcitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('sitemap_url', models.URLField(blank=True, default='', max_length=2048)),
                ('crawl_limit', models.IntegerField(default=200)),
                ('total_urls', models.IntegerField(default=0)),
                ('indexed_count', models.IntegerField(default=0)),
                ('redirect_count', models.IntegerField(default=0)),
                ('queued_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('avg_lcp_ms', models.IntegerField(blank=True, null=True)),
                ('avg_fcp_ms', models.IntegerField(blank=True, null=True)),
                ('avg_ttfb_ms', models.IntegerField(blank=True, null=True)),
                ('avg_ai_score', models.IntegerField(blank=True, null=True)),
                ('truncated', models.BooleanField(default=False)),
                ('discovered_url_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_audits', to='analyzer.analysisrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(max_length=2048)),
                ('status_code', models.IntegerField(default=0)),
                ('ts', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('cloudflare', 'Cloudflare'), ('vercel', 'Vercel'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_log_entries', to='analyzer.analysisrun')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['analysis_run', 'bot_name'], name='analyzer_ag_analysi_a4b830_idx')],
            },
        ),
        migrations.CreateModel(
            name='SitemapAuditPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('path', models.CharField(blank=True, default='', max_length=2048)),
                ('final_url', models.URLField(blank=True, default='', max_length=2048)),
                ('state', models.CharField(choices=[('crawled', 'Crawled'), ('redirect', 'Redirect'), ('queued', 'Queued'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('status_code', models.IntegerField(db_index=True, default=0)),
                ('redirect_count', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('meta_description', models.CharField(blank=True, default='', max_length=1024)),
                ('h1_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('text_ratio', models.FloatField(default=0.0)),
                ('content_length', models.IntegerField(default=0)),
                ('lcp_ms', models.IntegerField(blank=True, null=True)),
                ('fcp_ms', models.IntegerField(blank=True, null=True)),
                ('ttfb_ms', models.IntegerField(blank=True, null=True)),
                ('server_ms', models.IntegerField(blank=True, null=True)),
                ('resource_count', models.IntegerField(default=0)),
                ('resource_bytes', models.IntegerField(default=0)),
                ('link_count_total', models.IntegerField(default=0)),
                ('link_count_internal', models.IntegerField(default=0)),
                ('link_count_external', models.IntegerField(default=0)),
                ('jsonld_count', models.IntegerField(default=0)),
                ('has_canonical', models.BooleanField(default=False)),
                ('has_og', models.BooleanField(default=False)),
                ('is_noindex', models.BooleanField(default=False)),
                ('robots_allows_gptbot', models.BooleanField(default=True)),
                ('robots_allows_claudebot', models.BooleanField(default=True)),
                ('robots_allows_perplexitybot', models.BooleanField(default=True)),
                ('ai_score', models.IntegerField(default=0)),
                ('severity', models.CharField(choices=[('ok', 'Ok'), ('warn', 'Warn'), ('fail', 'Fail')], db_index=True, default='ok', max_length=8)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('error_message', models.CharField(blank=True, default='', max_length=512)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='analyzer.sitemapaudit')),
            ],
            options={
                'ordering': ['audit_id', 'id'],
                'indexes': [models.Index(fields=['audit', 'state'], name='analyzer_si_audit_i_c57641_idx'), models.Index(fields=['audit', 'severity'], name='analyzer_si_audit_i_dd2b19_idx')],
            },
        ),
    ]
