# Generated by Django 5.2.11 on 2026-04-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0028_sitemapaudit_agentlogentry_sitemapauditpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_urls', models.IntegerField(default=0)),
                ('healthy_count', models.IntegerField(default=0)),
                ('warn_count', models.IntegerField(default=0)),
                ('broken_count', models.IntegerField(default=0)),
                ('discovered_from_sitemap', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_watches', to='analyzer.analysisrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaWatchPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('path', models.CharField(blank=True, default='', max_length=2048)),
                ('page_kind', models.CharField(blank=True, default='', max_length=32)),
                ('status_code', models.IntegerField(default=0)),
                ('schema_types', models.JSONField(blank=True, default=list)),
                ('jsonld_count', models.IntegerField(default=0)),
                ('raw_jsonld', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('ok', 'Ok'), ('warn', 'Warn'), ('fail', 'Fail')], db_index=True, default='ok', max_length=8)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('fix_targets', models.JSONField(blank=True, default=list)),
                ('error_message', models.CharField(blank=True, default='', max_length=512)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='analyzer.schemawatch')),
            ],
            options={
                'ordering': ['watch_id', 'id'],
                'indexes': [models.Index(fields=['watch', 'severity'], name='analyzer_sc_watch_i_cd17f1_idx')],
            },
        ),
    ]
