# Generated by Django 5.2.11 on 2026-04-24 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0029_schemawatch_schemawatchpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_queries', models.IntegerField(default=0)),
                ('queries_done', models.IntegerField(default=0)),
                ('avg_brand_mentions', models.FloatField(default=0.0)),
                ('avg_top3_brand_rate', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_audits', to='analyzer.analysisrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('rank', models.IntegerField(default=0)),
                ('brand_mention_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='analyzer.rankaudit')),
            ],
            options={
                'ordering': ['audit_id', 'rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RankResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('google', 'Google'), ('reddit', 'Reddit'), ('quora', 'Quora')], db_index=True, max_length=16)),
                ('position', models.IntegerField()),
                ('url', models.URLField(max_length=2048)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('snippet', models.TextField(blank=True, default='')),
                ('is_brand_mentioned', models.BooleanField(default=False)),
                ('competitors_mentioned', models.JSONField(blank=True, default=list)),
                ('upvotes', models.IntegerField(blank=True, null=True)),
                ('subreddit', models.CharField(blank=True, default='', max_length=120)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analyzer.rankquery')),
            ],
            options={
                'ordering': ['query_id', 'surface', 'position'],
                'indexes': [models.Index(fields=['query', 'surface', 'position'], name='analyzer_ra_query_i_c6952c_idx')],
            },
        ),
    ]
