# Generated by Django 5.2.11 on 2026-04-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0030_rankaudit_rankquery_rankresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankresult',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rankresult',
            name='response_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rankresult',
            name='surface',
            field=models.CharField(choices=[('google', 'Google'), ('reddit', 'Reddit'), ('quora', 'Quora'), ('ai', 'Ai')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='rankresult',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
