# Generated by Django 5.2.11 on 2026-04-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0031_rankresult_engine_rankresult_response_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankresult',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
    ]
