# Generated by Django 5.2.11 on 2026-04-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0027_prompttrack_intent_prompt_type'),
        ('analyzer', '0032_rankresult_sentiment'),
    ]

    operations = [
    ]
