# Generated by Django 5.2.11 on 2026-04-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0033_merge_20260424_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttrack',
            name='intent',
            field=models.CharField(choices=[('brand', 'Brand'), ('informational', 'Information'), ('transactional', 'Transactional')], default='informational', max_length=20),
        ),
        migrations.AlterField(
            model_name='prompttrack',
            name='prompt_type',
            field=models.CharField(choices=[('organic', 'Organic'), ('branded', 'Brand'), ('competitive', 'Competition')], default='organic', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledanalysis',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
    ]
