# Generated by Django 5.2.6 on 2026-04-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0034_alter_prompttrack_intent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklinkSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("referring_domains", models.IntegerField(default=0)),
                ("backlinks", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=0)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-referring_domains"],
            },
        ),
    ]
