# Generated by Django 5.2.11 on 2026-04-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0033_merge_20260424_0933'),
        ('analyzer', '0034_alter_prompttrack_intent_and_more'),
    ]

    operations = [
    ]
