# Generated by Django 5.2.6 on 2026-04-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0035_backlinksnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklinkOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("rationale", models.CharField(blank=True, default="", max_length=400)),
                ("submit_url", models.URLField(max_length=2048)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("directory", "Directory"),
                            ("review", "Review Site"),
                            ("press", "Press / Media"),
                            ("forum", "Community / Forum"),
                            ("resource", "Resource Page"),
                            ("other", "Other"),
                        ],
                        default="directory",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("submitted", "Submitted"),
                            ("live", "Live"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="suggested",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("live_url", models.URLField(blank=True, default="", max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlink_opportunities",
                        to="analyzer.prompttrack",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["prompt_track", "status"],
                        name="analyzer_ba_prompt__f32423_idx",
                    )
                ],
            },
        ),
    ]
