# Generated by Django 5.2.11 on 2026-04-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0036_backlinkopportunity"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklinkProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "homepage_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="BacklinkProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=120)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("guest_post", "Guest Post"),
                            ("niche_edit", "Niche Edit"),
                            ("sponsored", "Sponsored Post"),
                            ("citation", "Citation / Listing"),
                            ("other", "Other"),
                        ],
                        default="guest_post",
                        max_length=20,
                    ),
                ),
                ("domain_authority", models.IntegerField(blank=True, null=True)),
                ("domain_rank", models.IntegerField(blank=True, null=True)),
                ("monthly_traffic", models.IntegerField(blank=True, null=True)),
                ("niche_tags", models.JSONField(blank=True, default=list)),
                ("language", models.CharField(default="en", max_length=8)),
                ("country", models.CharField(blank=True, default="", max_length=8)),
                ("do_follow", models.BooleanField(default=True)),
                ("wholesale_price_cents", models.IntegerField(default=0)),
                ("retail_price_cents", models.IntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("lead_time_days", models.IntegerField(default=7)),
                ("extras", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="analyzer.backlinkprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-domain_authority", "domain"],
            },
        ),
        migrations.CreateModel(
            name="BacklinkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("target_url", models.URLField(max_length=2048)),
                ("anchor_text", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_payment", "Pending payment"),
                            ("queued", "Queued with provider"),
                            ("in_progress", "In progress"),
                            ("delivered", "Delivered"),
                            ("rejected", "Rejected"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("price_cents", models.IntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "provider_order_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("proof_url", models.URLField(blank=True, default="", max_length=2048)),
                ("notes_for_provider", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "payment_intent_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ordered_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlink_orders",
                        to="analyzer.analysisrun",
                    ),
                ),
                (
                    "prompt_track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlink_orders",
                        to="analyzer.prompttrack",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="analyzer.backlinkproduct",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="analyzer.backlinkprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="backlinkproduct",
            index=models.Index(
                fields=["provider", "domain"], name="analyzer_ba_provide_3ca0a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backlinkproduct",
            index=models.Index(
                fields=["link_type"], name="analyzer_ba_link_ty_729259_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="backlinkproduct",
            constraint=models.UniqueConstraint(
                fields=("provider", "sku"), name="uniq_provider_sku"
            ),
        ),
        migrations.AddIndex(
            model_name="backlinkorder",
            index=models.Index(
                fields=["user_email", "status"], name="analyzer_ba_user_em_7facf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backlinkorder",
            index=models.Index(fields=["status"], name="analyzer_ba_status_185450_idx"),
        ),
    ]
