# Generated by Django 5.2.11 on 2026-05-01 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0037_backlinkprovider_backlinkproduct_backlinkorder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptSchemaArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("faq", "FAQ"),
                            ("article", "Article"),
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("answer", "Direct answer"),
                        ],
                        max_length=24,
                    ),
                ),
                ("output", models.TextField()),
                ("explanation", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_artifacts",
                        to="analyzer.prompttrack",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prompt_track", "schema_type"],
                        name="analyzer_pr_prompt__0a2b8e_idx",
                    )
                ],
                "unique_together": {("prompt_track", "schema_type")},
            },
        ),
    ]
