# Generated by Django 5.2.6 on 2026-05-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0039_alter_autofixjob_status_brandkit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overview", models.JSONField(default=dict)),
                ("top_keywords", models.JSONField(default=list)),
                ("top_pages", models.JSONField(default=list)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_analytics",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
        ),
    ]
