# Generated by Django 5.2.6 on 2026-05-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0040_domainanalyticssnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainanalyticssnapshot",
            name="geo_distribution",
            field=models.JSONField(default=dict),
        ),
    ]
