# Generated by Django 5.2.6 on 2026-05-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0035_merge_20260424_0957"),
        ("analyzer", "0041_domainanalyticssnapshot_geo_distribution"),
    ]

    operations = []
