# Generated by Django 5.2.6 on 2026-05-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0042_merge_20260504_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048)),
                ("title", models.CharField(max_length=255)),
                ("rationale", models.TextField()),
                (
                    "target_field",
                    models.CharField(
                        choices=[
                            ("title", "title"),
                            ("meta_description", "meta_description"),
                            ("body_html", "body_html"),
                            ("schema_jsonld", "schema_jsonld"),
                        ],
                        max_length=32,
                    ),
                ),
                ("current_excerpt", models.TextField(blank=True)),
                ("proposed_value", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "proposed"),
                            ("used", "used"),
                            ("dismissed", "dismissed"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_suggestions",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis_run", "url", "status"],
                        name="analyzer_co_analysi_78df14_idx",
                    )
                ],
            },
        ),
    ]
