# Generated by Django 5.2.11 on 2026-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0043_contentsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='storefront_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
