# Generated by Django 5.2.6 on 2026-05-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0043_contentsuggestion"),
        ("analyzer", "0044_analysisrun_storefront_password"),
    ]

    operations = []
