# Generated by Django 5.2.11 on 2026-06-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0046_drop_prompttrack_mentioned_competitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='daily_priority_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_top_fix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
