# Generated by Django 5.2.11 on 2026-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0048_satelliteblogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('research', 'Research'), ('listicals', 'Listicals'), ('market_trends', 'Market Trends'), ('comparison', 'Comparison'), ('step_guide', 'Step Guide')], db_index=True, max_length=20)),
                ('slug', models.CharField(db_index=True, max_length=160)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=2048)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('brand_url', models.URLField(blank=True, default='', max_length=2048)),
                ('brand_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source', models.CharField(default='signalor', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='analyzer_bl_site_944b26_idx'), models.Index(fields=['brand_ref'], name='analyzer_bl_brand_r_f53103_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='uniq_blogpost_site_slug')],
            },
        ),
        migrations.DeleteModel(
            name='SatelliteBlogPost',
        ),
    ]
