"""Raw crawler/AI files on a Shopify storefront.

What this covers:
  - robots.txt          — editable via theme asset templates/robots.txt.liquid
                          (only file Shopify routes at the root path)
  - llms-txt            — Shopify Page at /pages/llms-txt
  - humans-txt          — Shopify Page at /pages/humans-txt
  - ads-txt             — Shopify Page at /pages/ads-txt

Why mix two mechanisms: Shopify's storefront router only maps a fixed
set of theme templates to root URLs (robots.txt, sitemap.xml). For any
other file you can't have `/<file>.txt` at the root — the closest legal
URL is a Shopify Page at `/pages/<handle>` (handles can't contain dots,
so we use hyphens: `llms-txt`).

Public surface:
    list_raw_files(integration) -> list[dict]
    upsert_raw_file(integration, name, content) -> dict
"""

from __future__ import annotations

import json
import logging
from typing import Any

import requests

from .shopify import API_VERSION, normalize_shop_domain

logger = logging.getLogger(__name__)

TIMEOUT_SECONDS = 20

# Definitions for each raw file: how it's stored, what URL it ends up at,
# what the default content template should be when the merchant creates
# it for the first time.
# Chrome-stripping via custom Liquid templates was attempted but doesn't
# work on Online Store 2.0 themes (Dawn etc.) — Shopify always falls
# back to the JSON template, wrapping the page in theme.liquid. See
# commit notes. The page-kind raw files end up rendered with the theme
# chrome; for true chrome-less serving we'd need the Signalor Shopify
# Remix app's App Proxy mechanism.

RAW_FILES: dict[str, dict[str, Any]] = {
    "robots": {
        "label": "robots.txt",
        "kind": "theme_asset",
        "asset_key": "templates/robots.txt.liquid",
        "url_path": "/robots.txt",
        "default_template": (
            "# robots.txt generated by Signalor\n"
            "# This file overrides Shopify's default robots.txt.\n"
            "{% for group in robots.default_groups %}\n"
            "  {{- group.user_agent }}\n"
            "  {% for rule in group.rules %}{{ rule }}\n  {% endfor %}\n"
            "  {%- if group.sitemap != blank %}\n"
            "  {{ group.sitemap }}\n"
            "  {%- endif %}\n"
            "{% endfor %}\n"
        ),
    },
    "llms": {
        "label": "llms.txt",
        "kind": "page",
        "handle": "llms-txt",
        "title": "llms.txt",
        "url_path": "/pages/llms-txt",
        "default_template": (
            "# {brand}\n\n"
            "> One-line description of what {brand} sells or does.\n\n"
            "## About\n"
            "Longer description here. What you make, who it's for.\n\n"
            "## Important pages\n"
            "- [/](https://{shop}/) — homepage\n"
            "- [/products](https://{shop}/products) — all products\n"
        ),
    },
    "humans": {
        "label": "humans.txt",
        "kind": "page",
        "handle": "humans-txt",
        "title": "humans.txt",
        "url_path": "/pages/humans-txt",
        "default_template": (
            "/* TEAM */\n"
            "Owner: {brand}\n\n"
            "/* THANKS */\n"
            "Built with Shopify and Signalor\n\n"
            "/* SITE */\n"
            "Last update: today\n"
            "Standards: HTML5, CSS3\n"
        ),
    },
    "ads": {
        "label": "ads.txt",
        "kind": "page",
        "handle": "ads-txt",
        "title": "ads.txt",
        "url_path": "/pages/ads-txt",
        "default_template": (
            "# ads.txt — Authorized Digital Sellers\n"
            "# Replace with your real advertiser entries. Each line:\n"
            "# <domain>, <publisher_id>, <relationship>, <cert_id>\n"
        ),
    },
}


class RawFileError(Exception):
    """Raised when a raw-file operation can't proceed for a recoverable
    reason (no theme, unreachable shop, etc.). Surfaceable to the client."""


def known_names() -> list[str]:
    return list(RAW_FILES.keys())


# ─── Shopify auth/headers ─────────────────────────────────────────────────


def _shop(integration) -> str:
    md = integration.metadata or {}
    domain = md.get("shop_domain", "")
    if not domain:
        raise RawFileError("Shopify integration is missing shop_domain metadata.")
    return normalize_shop_domain(domain)


def _headers(integration) -> dict[str, str]:
    token = integration.get_access_token()
    if not token:
        raise RawFileError("Shopify integration has no access token.")
    return {
        "X-Shopify-Access-Token": token,
        "Content-Type": "application/json",
    }


def _api(integration, method: str, path: str, *, params=None, payload=None):
    shop = _shop(integration)
    url = f"https://{shop}/admin/api/{API_VERSION}{path}"
    try:
        resp = requests.request(
            method,
            url,
            headers=_headers(integration),
            params=params,
            data=json.dumps(payload) if payload is not None else None,
            timeout=TIMEOUT_SECONDS,
        )
    except requests.RequestException as exc:
        raise RawFileError(f"Couldn't reach Shopify: {exc}") from exc
    if resp.status_code == 401:
        raise RawFileError("Shopify access token rejected. Reconnect the store.")
    if resp.status_code == 404:
        return None  # caller decides — for "does this exist?" checks
    if resp.status_code == 422:
        # Unprocessable entity — Shopify rejected the body (e.g., handle in use).
        try:
            details = resp.json()
        except Exception:
            details = {"errors": resp.text}
        raise RawFileError(f"Shopify rejected the request: {details}")
    if resp.status_code >= 400:
        raise RawFileError(f"Shopify Admin API returned HTTP {resp.status_code}.")
    if resp.status_code == 204 or not resp.content:
        return {}
    return resp.json()


# ─── Theme-asset path (robots.txt) ────────────────────────────────────────


def _active_theme_id(integration) -> int:
    data = _api(integration, "GET", "/themes.json") or {}
    for t in data.get("themes", []) or []:
        if t.get("role") == "main":
            return int(t["id"])
    raise RawFileError("No main theme found on this Shopify store.")


def _read_theme_asset(integration, theme_id: int, asset_key: str) -> str:
    data = _api(
        integration,
        "GET",
        f"/themes/{theme_id}/assets.json",
        params={"asset[key]": asset_key},
    )
    if not data:
        return ""
    return (data.get("asset") or {}).get("value") or ""


def _write_theme_asset(integration, theme_id: int, asset_key: str, value: str) -> None:
    _api(
        integration,
        "PUT",
        f"/themes/{theme_id}/assets.json",
        payload={"asset": {"key": asset_key, "value": value}},
    )


# ─── Pages path (llms-txt, humans-txt, ads-txt) ───────────────────────────


def _find_page(integration, handle: str) -> dict | None:
    """Pages API has no direct lookup by handle on the REST endpoint, so we
    list and filter. With handles used here being unique strings, this is
    fast enough — typical shops have <50 pages."""
    data = _api(integration, "GET", "/pages.json", params={"limit": 250})
    if not data:
        return None
    for p in data.get("pages", []) or []:
        if p.get("handle") == handle:
            return p
    return None


def _create_page(integration, handle: str, title: str, body_html: str) -> dict:
    data = _api(
        integration,
        "POST",
        "/pages.json",
        payload={"page": {"handle": handle, "title": title, "body_html": body_html, "published": True}},
    )
    return (data or {}).get("page") or {}


def _update_page(integration, page_id: int, body_html: str) -> dict:
    data = _api(
        integration,
        "PUT",
        f"/pages/{page_id}.json",
        payload={"page": {"id": page_id, "body_html": body_html}},
    )
    return (data or {}).get("page") or {}


# ─── Public API ───────────────────────────────────────────────────────────


def _shop_branding_defaults(integration) -> dict[str, str]:
    """Best-effort brand/shop placeholders for the default-content templates."""
    md = integration.metadata or {}
    shop = md.get("shop_domain", "your-store.myshopify.com")
    brand = md.get("shop_name") or shop.split(".")[0]
    return {"brand": brand, "shop": shop}


def list_raw_files(integration) -> list[dict]:
    """Return current status of every supported raw file on the shop."""
    placeholders = _shop_branding_defaults(integration)
    shop = _shop(integration)

    # Resolve the active theme once — used only if any theme_asset entries
    # are present. Lazy: don't fail the whole list if themes call breaks.
    theme_id: int | None = None
    try:
        theme_id = _active_theme_id(integration)
    except RawFileError:
        theme_id = None

    items: list[dict] = []
    for name, cfg in RAW_FILES.items():
        url = f"https://{shop}{cfg['url_path']}"
        present = False
        content = ""
        try:
            if cfg["kind"] == "theme_asset":
                if theme_id is not None:
                    content = _read_theme_asset(integration, theme_id, cfg["asset_key"])
                    present = bool(content)
            elif cfg["kind"] == "page":
                page = _find_page(integration, cfg["handle"])
                if page:
                    present = True
                    content = page.get("body_html", "") or ""
        except RawFileError as exc:
            logger.info("raw-files: %s lookup failed: %s", name, exc)
            content = ""
            present = False

        # str.format() can't be used here — robots.txt's default template
        # contains Liquid braces ({% ... %} / {{ ... }}) that Python's format
        # spec rejects. Use a plain replace for our two placeholders instead.
        default = cfg.get("default_template") or ""
        for k, v in placeholders.items():
            default = default.replace("{" + k + "}", v)
        items.append(
            {
                "name": name,
                "label": cfg["label"],
                "kind": cfg["kind"],
                "url": url,
                "present": present,
                "content": content,
                "default_template": default,
            }
        )
    return items


def upsert_raw_file(integration, name: str, content: str) -> dict:
    """Create or update a raw file. Returns the new state dict."""
    if name not in RAW_FILES:
        raise RawFileError(f"Unknown raw file: {name}.")
    cfg = RAW_FILES[name]
    content = content or ""

    if cfg["kind"] == "theme_asset":
        theme_id = _active_theme_id(integration)
        _write_theme_asset(integration, theme_id, cfg["asset_key"], content)
        return {"name": name, "kind": "theme_asset", "present": True, "content": content}

    if cfg["kind"] == "page":
        existing = _find_page(integration, cfg["handle"])
        if existing:
            _update_page(integration, int(existing["id"]), content)
        else:
            _create_page(integration, cfg["handle"], cfg["title"], content)
        return {"name": name, "kind": "page", "present": True, "content": content}

    raise RawFileError(f"Unsupported raw-file kind: {cfg['kind']!r}")
