# Generated by Django 5.2.6 on 2026-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisibilityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=255)),
                ("brand_url", models.URLField(max_length=2048)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checking_google", "Checking Google"),
                            ("checking_reddit", "Checking Reddit"),
                            ("checking_medium", "Checking Medium"),
                            ("scoring", "Scoring"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("google_score", models.FloatField(blank=True, null=True)),
                ("google_details", models.JSONField(blank=True, default=dict)),
                ("reddit_score", models.FloatField(blank=True, null=True)),
                ("reddit_details", models.JSONField(blank=True, default=dict)),
                ("medium_score", models.FloatField(blank=True, null=True)),
                ("medium_details", models.JSONField(blank=True, default=dict)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="visibility__email_83a091_idx"),
                    models.Index(
                        fields=["status"], name="visibility__status_050382_idx"
                    ),
                ],
            },
        ),
    ]
