# Generated by Django 5.2.11 on 2026-05-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingDripState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('amplitude_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('geo_score', models.FloatField(blank=True, null=True)),
                ('fix_count', models.IntegerField(blank=True, null=True)),
                ('top_competitor', models.CharField(blank=True, default='', max_length=255)),
                ('competitor_list', models.TextField(blank=True, default='')),
                ('cms_platform', models.CharField(blank=True, default='', max_length=32)),
                ('top_recommendation_title', models.CharField(blank=True, default='', max_length=512)),
                ('issue_count', models.IntegerField(blank=True, null=True)),
                ('competitor_count', models.IntegerField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.IntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('suppressed', models.BooleanField(default=False)),
                ('suppressed_reason', models.CharField(blank=True, default='', max_length=32)),
                ('suppressed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['suppressed', 'current_step'], name='drip_pricin_suppres_a4b4e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DripSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('subject_variant', models.CharField(max_length=4)),
                ('subject', models.CharField(max_length=998)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='drip.pricingdripstate')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['state', 'step'], name='drip_dripse_state_i_28f678_idx')],
            },
        ),
    ]
