# Generated by Django 5.2.11 on 2026-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingdripstate',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
