# Generated by Django 5.2.11 on 2026-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0002_pricingdripstate_failure_count'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dripsendlog',
            constraint=models.UniqueConstraint(condition=models.Q(('success', True)), fields=('state', 'step'), name='drip_one_successful_send_per_step'),
        ),
    ]
