# Generated by Django 5.2.11 on 2026-06-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analyzer", "0046_drop_prompttrack_mentioned_competitors"),
        ("organizations", "0004_organization_normalized_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                (
                    "account_login",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "connect_slug",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "repo_full_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("repositories", models.JSONField(blank=True, default=list)),
                (
                    "default_branch",
                    models.CharField(blank=True, default="main", max_length=255),
                ),
                ("repo_profile", models.JSONField(blank=True, default=dict)),
                (
                    "repo_profile_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_installations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GithubFixJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finding_codes", models.JSONField(blank=True, default=list)),
                (
                    "branch_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("pr_number", models.IntegerField(blank=True, null=True)),
                ("pr_url", models.URLField(blank=True, default="", max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("open", "Open"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("files_changed", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("score_before", models.FloatField(blank=True, null=True)),
                ("score_after", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_fix_jobs",
                        to="analyzer.analysisrun",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fix_jobs",
                        to="github_agent.githubinstallation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="githubinstallation",
            index=models.Index(
                fields=["installation_id"], name="github_agen_install_1efc24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubinstallation",
            index=models.Index(
                fields=["organization", "is_active"],
                name="github_agen_organiz_0cfb78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="githubinstallation",
            index=models.Index(
                fields=["connect_slug"], name="github_agen_connect_b1fa03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubfixjob",
            index=models.Index(
                fields=["analysis_run", "-created_at"],
                name="github_agen_analysi_b60ab2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="githubfixjob",
            index=models.Index(fields=["status"], name="github_agen_status_b4497e_idx"),
        ),
        migrations.AddIndex(
            model_name="githubfixjob",
            index=models.Index(
                fields=["pr_number"], name="github_agen_pr_numb_604232_idx"
            ),
        ),
    ]
