# Generated by Django 5.2.11 on 2026-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubfixjob",
            name="reasoning",
            field=models.TextField(blank=True, default=""),
        ),
    ]
