# Generated by Django 5.2.11 on 2026-02-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["owner_email"], name="organizatio_owner_e_2fc24a_idx"
            ),
        ),
    ]
