# Generated by Django 5.2.6 on 2026-05-29 10:00

from django.db import migrations, models


def backfill_normalized_url(apps, schema_editor):
    """Compute normalized_url for every existing Organization row."""
    from apps.organizations.utils import normalize_url

    Organization = apps.get_model("organizations", "Organization")
    rows = []
    for org in Organization.objects.all().only("id", "url"):
        nu = normalize_url(org.url or "")
        if nu:
            org.normalized_url = nu
            rows.append(org)
    if rows:
        Organization.objects.bulk_update(rows, ["normalized_url"], batch_size=500)


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op — the field gets dropped by the schema reverse."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_remove_org_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="normalized_url",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["owner_email", "normalized_url"],
                name="organizatio_owner_e_dfeb81_idx",
            ),
        ),
        migrations.RunPython(backfill_normalized_url, noop_reverse),
    ]
